/* v2 local UX prototype: no API calls, storage, cookies, emails or analytics. */
(() => {
  if (!(location.hostname === 'lee-bunya.github.io' && location.pathname.startsWith('/bunya-team-preview/')) && !['localhost','127.0.0.1'].includes(location.hostname)) return;
  const outcomes=[['advice_admin','Reduce advice administration'],['reviews','Keep reviews and follow-up on track'],['visibility','Improve practice visibility'],['capacity','Grow without adding the same administration'],['marketing','Improve marketing consistency'],['communications','Connect calls and meeting notes'],['exploring','Just exploring']];
  const roles=[['principal','Principal / Owner'],['adviser','Adviser'],['practice_manager','Practice Manager'],['operations','Operations'],['other','Other']];
  const ranges=[['under_300','Under 300'],['300_800','300–800'],['800_1500','800–1,500'],['1500_plus','1,500+']];
  const preferences=[['overview','A short overview of the business benefits'],['walkthrough','A practical walkthrough'],['customer_examples','Customer examples and implementation guidance'],['technical_detail','Detailed information about features and integrations']];
  function create(kind){
    const demo=kind==='demo',prefix=demo?'bd':'bt';
    const input=(name,label,required=true,type='text',auto='')=>`<div class="bd-field"><label for="${prefix}-${name}">${label}${required?' <span aria-hidden="true">*</span>':''}</label><input id="${prefix}-${name}" name="${name}" type="${type}" ${required?'required':''} ${auto?`autocomplete="${auto}"`:''} maxlength="${type==='email'?254:150}"></div>`;
    const select=(name,label,values,required=true)=>`<div class="bd-field"><label for="${prefix}-${name}">${label}${required?' <span aria-hidden="true">*</span>':''}</label><select id="${prefix}-${name}" name="${name}" ${required?'required':''}><option value="">Select an option</option>${values.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div>`;
    const privacy=`<a href="https://bunya.ai/privacy/" target="_blank" rel="noopener">privacy notice</a>`;
    const dialog=document.createElement('dialog');dialog.className='bd-modal';dialog.setAttribute('aria-labelledby',prefix+'-title');dialog.dataset.journey=kind;
    dialog.innerHTML=`<div class="bd-top"><span class="bd-brand">bunya.ai</span><button class="bd-close" type="button" aria-label="Close ${demo?'demo':'test drive'} form">×</button></div><div class="bd-content">
    <p class="bd-preview">Team preview · No details are sent or saved outside this tab. Calendar, progress saving and emails are simulated.</p>
    <ol class="bd-steps" aria-label="Request progress"><li>Email</li><li>Your firm</li><li>Your priorities</li><li>Review</li></ol>
    <h2 id="${prefix}-title" tabindex="-1"></h2><p class="bd-description"></p><form novalidate><p class="bd-note">Fields marked * are required.</p><p class="bd-error" role="alert" id="${prefix}-error" hidden></p>
    <fieldset data-step="email"><legend hidden>Your email</legend>${input('work_email','Work email',true,'email','email')}
    <div class="bd-calendar"><strong>Proposed live progress notice</strong>When you continue, we save your email and progress so you can return to this request. See our ${privacy}. This is not a marketing subscription.</div><p class="bd-note">In this preview, closing and reopening keeps your answers in this tab only. Reloading clears them.</p></fieldset>
    <fieldset data-step="firm" hidden disabled><legend hidden>About your firm</legend><div class="bd-grid">${input('first_name','First name',true,'text','given-name')}${demo?input('last_name','Last name',true,'text','family-name'):''}${input('firm_name','Firm name',true,'text','organization')}${select('role_title','Your role',roles)}${select('client_groups_band','Number of client groups',ranges)}</div><p class="bd-note">An approximate count is fine. A client group is a household or related group you advise.</p></fieldset>
    <fieldset data-step="priorities" hidden disabled><legend hidden>Your priorities</legend>
    ${select('primary_outcome','What would you most like to improve?',outcomes)}
    ${demo?select('product_interest','What would you like to explore?',[['command_centre','Command Centre'],['broadcast_hq','Broadcast HQ'],['bunya_voice','Bunya Voice'],['whole_system','The whole system'],['not_sure','Not sure yet']])+select('decision_stage','Where are you in the process?',[['exploring','Just exploring'],['comparing','Comparing options'],['planning_3mo','Planning a change in the next three months'],['ready','Ready to discuss implementation']])+`<details class="bd-extra"><summary>Add more context</summary>`+select('organisation_type','Which best describes your organisation?',[['single_practice','A single advice practice'],['multi_office','An advice firm with multiple offices'],['licensee_group','A licensee or advice group'],['other','Other']],false)+select('current_software','What do you mainly run on today?',[['xplan','Xplan'],['worksorted','Worksorted'],['adviserlogic','AdviserLogic'],['midwinter','Midwinter'],['other','Spreadsheets / other']],false)+input('phone','Phone',false,'tel','tel')+`<div class="bd-field"><label for="${prefix}-notes">Anything else we should know?</label><textarea id="${prefix}-notes" name="focus_notes" rows="3" maxlength="2000"></textarea></div></details>`:'<p class="bd-note">Your test drive is for Command Centre.</p>'}
    <label class="bd-consent"><input name="consent" type="checkbox" required><span>I agree to Bunya using these details to respond to this request, as described in the ${privacy}. *</span></label>
    <label class="bd-consent"><input name="marketing_consent" type="checkbox"><span>Also send me Bunya tips and product updates. I can unsubscribe at any time.</span></label></fieldset>
    <fieldset data-step="review" hidden disabled><legend hidden>Review request</legend><dl class="bd-review"></dl><p class="bd-note">The next button simulates a successful submission. Nothing will be sent.</p></fieldset>
    <fieldset data-step="booking" hidden disabled><legend hidden>Calendar preview</legend><div class="bd-calendar"><strong>Meet the Bunya sales team for a guided demo.</strong><p>Monday–Friday · 10am–4pm Melbourne time<br>1-hour session · 1-hour buffer afterwards</p><p>Host: sales@bunya.ai</p><p>This is a calendar placeholder. It does not show availability or create an appointment.</p></div><button type="button" class="bd-back bd-later">Leave booking for later →</button></fieldset>
    <fieldset data-step="preferences" hidden disabled><legend>What would help you evaluate Bunya?</legend><p class="bd-note">Choose any that would be useful. This does not change your marketing permission.</p>${preferences.map(([v,l])=>`<label class="bd-option"><input type="checkbox" name="content_preferences" value="${v}"><span>${l}</span></label>`).join('')}<button type="button" class="bd-back bd-skip">Skip for now</button></fieldset>
    <fieldset data-step="done" hidden disabled><legend hidden>Preview complete</legend><div class="bd-calendar"><strong>Preview complete.</strong><p class="bd-result"></p><p>No CRM record, email or appointment has been created. No nurture automation is running.</p></div></fieldset>
    <div class="bd-actions"><button class="bd-back bd-prev" type="button">← Back</button><button class="bd-next" type="submit">Continue →</button></div></form><p class="bd-sim" aria-live="polite">Simulated status: not started</p></div>`;
    document.body.append(dialog);
    let step='email',trigger=null,oldOverflow='',status='not_started',preferenceStatus='not_answered';
    const form=dialog.querySelector('form'),title=dialog.querySelector('h2'),err=dialog.querySelector('.bd-error'),order=['email','firm','priorities','review'];
    const titles={email:demo?'Let’s start with your email.':'Try Command Centre.',firm:'A little about your firm.',priorities:'What matters most to you?',review:'Check your details.',booking:'Choose a time with our team.',preferences:'Make your next step useful.',done:'You’re all set to review the design.'};
    const descriptions={email:demo?'A walkthrough focused on your practice.':'Explore Command Centre at your own pace.',firm:'Help us understand your practice.',priorities:'We’ll focus on the outcome that matters to you.',review:'Go back to change anything before continuing.',booking:'Preview: enquiry accepted. Booking is a separate step.',preferences:demo?'Preview: booking confirmed. Preferences are a separate update.':'Preview: request accepted. Your access request does not depend on answering this question.',done:'Thank you for trying the local preview.'};
    function show(next,focus=true){step=next;dialog.querySelectorAll('[data-step]').forEach(el=>{el.hidden=el.dataset.step!==step;el.disabled=el.hidden;});title.textContent=titles[step];dialog.querySelector('.bd-description').textContent=descriptions[step];dialog.querySelector('.bd-steps').hidden=!order.includes(step);dialog.querySelectorAll('.bd-steps li').forEach((li,i)=>{li.removeAttribute('aria-current');if(order[i]===step)li.setAttribute('aria-current','step');li.classList.toggle('bd-done',i<order.indexOf(step));});dialog.querySelector('.bd-prev').hidden=!['firm','priorities','review'].includes(step);dialog.querySelector('.bd-next').textContent=({review:'Simulate submission →',booking:'Simulate booking →',preferences:'Save preferences (preview)',done:'Close preview'})[step]||'Continue →';dialog.querySelector('.bd-sim').textContent=`Simulated status: ${status.replaceAll('_',' ')} · Preferences: ${preferenceStatus.replaceAll('_',' ')}`;err.hidden=true;dialog.scrollTop=0;if(focus)title.focus();}
    function summary(){const list=dialog.querySelector('.bd-review');list.replaceChildren();for(const el of form.querySelectorAll('[data-step="email"] input,[data-step="firm"] input,[data-step="firm"] select,[data-step="priorities"] input,[data-step="priorities"] select,[data-step="priorities"] textarea')){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=el.name.replaceAll('_',' ');dd.textContent=el.type==='checkbox'?(el.checked?'Yes':'No'):el.tagName==='SELECT'?(el.value?el.selectedOptions[0].textContent:'Not specified'):(el.value||'Not provided');list.append(dt,dd);}if(!demo){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent='Product';dd.textContent='Command Centre';list.append(dt,dd);}}
    function finish(skipped){preferenceStatus=skipped?'skipped':'saved';const count=dialog.querySelectorAll('[name=content_preferences]:checked').length;dialog.querySelector('.bd-result').textContent=`Simulated request status: ${status.replaceAll('_',' ')}. ${skipped?'Content preferences skipped.':`${count} content preference${count===1?'':'s'} selected.`}`;show('done');}
    form.addEventListener('submit',e=>{e.preventDefault();const controls=[...dialog.querySelector(`[data-step="${step}"]`).querySelectorAll('input,select,textarea')];controls.forEach(c=>{if(c.type==='text'||c.type==='email')c.value=c.value.trim();c.removeAttribute('aria-invalid');c.removeAttribute('aria-describedby');});const invalid=controls.find(c=>!c.checkValidity());if(invalid){err.textContent=step==='email'?'Enter a valid work email address.':'Please complete the required fields and privacy acknowledgement.';err.hidden=false;invalid.setAttribute('aria-invalid','true');invalid.setAttribute('aria-describedby',prefix+'-error');invalid.focus();return;}
      if(step==='email'){status='started';show('firm');}else if(step==='firm'){status='in_progress';show('priorities');}else if(step==='priorities'){summary();show('review');}else if(step==='review'){status=demo?'booking_pending':'enquiry_submitted';show(demo?'booking':'preferences');}else if(step==='booking'){status='booked';show('preferences');}else if(step==='preferences'){if(!controls.some(c=>c.checked)){err.textContent='Choose a preference, or select Skip for now.';err.hidden=false;return;}finish(false);}else dialog.close();
    });
    dialog.querySelector('.bd-prev').addEventListener('click',()=>show(order[order.indexOf(step)-1]));dialog.querySelector('.bd-skip').addEventListener('click',()=>finish(true));dialog.querySelector('.bd-later').addEventListener('click',()=>{dialog.querySelector('.bd-result').textContent='Simulated enquiry retained as booking pending. No appointment was made. The content-preference question is deferred until after booking.';show('done');});dialog.querySelector('.bd-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow=oldOverflow;trigger?.focus();});
    document.addEventListener('click',e=>{const link=e.target.closest('a');if(!link||e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;if(!(demo?/book a demo/i:/test drive/i).test(link.textContent))return;e.preventDefault();e.stopImmediatePropagation();trigger=link;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();show(step);},true);
    show('email',false);
    if(document.body.dataset.previewForm===kind){oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();show('email');}
  }
  create('demo');create('test-drive');
})();
